Hm4
thepro545/hm4 pull request #1
Opened 2021-12-30 08:48 UTC by thepro545

2022-01-01 01:53 UTC, rmuhamedgaliev requested changes
Давай исправим замечания.

2022-01-01 01:53 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        while (numberDay <= 31) {
2 цикла это перебор для этой задачи, ее эффективнее можно решить при помощи цикла for c примерно таким условием

> int currentFriday = firstFriday; currentFriday <= 31; currentFriday += 7

2022-01-01 01:53 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        for (i = 0; i < yearAfter; i += cometFlight) {
тут правильнее будет начинать с yearBefore и условием будет достижение yearAfter и внутри проверять целочисленным делением на cometFlight, так алгоритм сделает меньшее количество итераций.

2022-01-01 01:53 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 9; i++){
На собеседованиях часто просят обойтись 2 переменными и 1 оператором вывода. Давай так попробуем реализовать ?

2022-01-02 08:41 UTC, thepro545 commented on src/ru/skypro/Main.java
> +        while (numberDay <= 31) {
Подправил

2022-01-02 08:41 UTC, thepro545 commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 9; i++){
Сделал

2022-01-02 08:42 UTC, thepro545 commented on src/ru/skypro/Main.java
> +        for (i = 0; i < yearAfter; i += cometFlight) {
Тут помощь нужна)

2022-01-02 08:42 UTC, thepro545 commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 9; i++){
Там еще по 3 дз сделал допы
https://github.com/thepro545/hm3/pull/2

2022-01-03 16:42 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        for (i = 0; i < yearAfter; i += cometFlight) {
ну логика примерно такая будет 

for (int i = yearBefore; i <= yearAfter; i++) {
if (i % 79 == 0) {
//todo: что-то сделать
}
}

2022-01-03 16:45 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 9; i++){
для 3 задания посылай пожалуйста отдельно в интерфейс skypro

2022-01-03 16:59 UTC, rmuhamedgaliev requested changes

2022-01-03 16:59 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +            if (i & cometFlight == 0) { // Какая-то парашная ошибка. Ибо снизу(в 4 задачке) всё работает
Тут так не работает. Ты пытаешься сделать битовую операцию - https://www.baeldung.com/java-bitwise-operators

А тебе нужна проверка деления без остатка 

i % cometFlight == 0

2022-01-03 16:59 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +                System.out.print("pong ");
тут пробел необязателен уже можно просто 

System.out.print("pong");

2022-01-03 16:59 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +            System.out.println(" ");
А тут достаточно просто перевод на новую строку 

System.out.println();

2022-01-03 16:59 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 11; i++){
Так делать нельзя, пиши итератор сразу в цикле

> for (int i = 1; i < 11; i++)

2022-01-03 17:05 UTC, thepro545 commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 9; i++){
Я послал. Но там ответа нет

2022-01-03 17:11 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 9; i++){
Ну все равно придется подождать, за другого наставника я не могу ответить и проверить (

2022-01-03 17:22 UTC, thepro545 commented on src/ru/skypro/Main.java
> +            if (i & cometFlight == 0) { // Какая-то парашная ошибка. Ибо снизу(в 4 задачке) всё работает
А, лол. Я походу спутал) вместо % поставил & и не заметил разницы

2022-01-03 17:22 UTC, thepro545 commented on src/ru/skypro/Main.java
> +                System.out.print("pong ");
ну он и не мешает) подправил

2022-01-03 17:23 UTC, thepro545 commented on src/ru/skypro/Main.java
> +            System.out.println(" ");
+

2022-01-03 17:23 UTC, thepro545 commented on src/ru/skypro/Main.java
> +        for (i = 1; i < 11; i++){
Я заменил i на q. Ибо int = i я вводил в первой задаче. Если правильно понял

2022-01-03 17:46 UTC, rmuhamedgaliev approved these changes
Принято! 💪

2022-01-03 17:50 UTC, merged